add rules and clean files
TomBerriot/dev-bot pull request #9
Opened 2020-02-04 22:22 UTC by Sata51

2020-02-04 23:01 UTC, TomBerriot requested changes
Thanks for your help :)

2020-02-04 23:01 UTC, TomBerriot commented on .prettierrc
> +  "tabWidth": 2,
Would it be okay to keep it to 4 ? :) 
I don't mind tabs but a width of 2 is very hard on my eyes ^^

2020-02-06 19:58 UTC, Sata51 commented
Change has been done :)
I haven't test all my changes :D

2020-02-15 00:12 UTC, TomBerriot approved these changes

2020-02-15 00:12 UTC, merged